### PR TITLE
feat: add isStdlib and fix getName

### PR DESCRIPTION
**Pull request by willemneal**
- `isStdlib` checks if the internal path of a source file matches any known stdlib paths.
- `getName` previously relied on the text from `node.range`, but this assumes that the range is accurate for the node, which for some transforms isn't true.

### CODE REVIEW

**Comment by willemneal** [comment]
I'm also updating `asc` as it has some breaking changes.  And updating CI since jest no longer  accepts node v13 and I decided to drop v14.

**Comment by yjhmelody** [comment]
why release a version that yet not merged this pr

**Comment by willemneal** [comment]
@yjhmelody It's a pre-release.  So you have to do `yarn add visitor-as@next` so normal users shouldn't notice.  I'm thinking of automating this in a `dev` branch, that will use semver to automatically make a pre-release.

**Comment by yjhmelody** [comment]
@willemneal Hi! Can you merge this PR and update to the latest dependencies and release a new version?

**Pull request merged**
